### ISSUE TITLE
Update actions to node20

### ISSUE THREAD

**Issue by jlaundry** [jlaundry/devcontainers-feature-azure-functions-core-tools#13]
Currently under observation, waiting https://github.com/devcontainers/action/issues/203

**Comment by nicholas-l** [comment]
I believe this is unblocked, the issue above looks like it should be closed with the release of `devcontainers/action@1.4.2` (since they don't have a changelog: https://github.com/devcontainers/action/compare/v1.4.1...v1.4.2). In this case, since you are using `devcontainers/actions@v1`, it *should* be using `1.4.2`.

**Comment by jlaundry** [comment]
@nicholas-l I think I sent you an email... if I got the address wrong, could you please email jlaundry at jlaundry dot com?
